# Site settings
title:          Ediz Baha | Blog
description:    "Ediz Baha | Blog"
url:            https://edizbaha.tk

# Author
author:
  name:         Ediz Baha
  email:        me@edizbaha.tk
  url:          https://edizbaha.tk

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  github: https://github.com/edizbaha
  twitter: https://twitter.com/edizbaha
  instagram: https://instagram.com/edizbaha
